apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: github
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: 10.38.64.139/nkp/docker.io/library/nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  namespace: github
  labels:
    app: mynginx
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: mynginx
